import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import Link from "next/link";
import { ArrowLeft } from "lucide-react";
import type { Metadata } from "next";

// Replace with your actual production URL if deploying
const siteUrl =
  process.env.NEXT_PUBLIC_SITE_URL || "https://gitaflow.vercel.app";
const disclaimerPageUrl = `${siteUrl}/disclaimer`;

export const metadata: Metadata = {
  title: "Disclaimer - Gita Flow",
  description:
    "Important disclaimer regarding the use of Gita Flow. Understand the limitations and responsibilities when using our AI-powered spiritual guidance.",
  alternates: {
    canonical: disclaimerPageUrl,
  },
  openGraph: {
    title: "Disclaimer - Gita Flow",
    description:
      "Important disclaimer regarding the use of Gita Flow. Understand the limitations and responsibilities when seeking guidance.",
    url: disclaimerPageUrl,
    type: "website",
    // images: [ // Optional: if you have a specific OG image for the disclaimer page
    //   {
    //     url: `${siteUrl}/og-disclaimer.png`,
    //     width: 1200,
    //     height: 630,
    //     alt: 'Gita Flow Disclaimer',
    //   },
    // ],
  },
  twitter: {
    title: "Disclaimer - Gita Flow",
    description:
      "Important disclaimer regarding the use of Gita Flow and its AI-generated spiritual guidance.",
    // images: [`${siteUrl}/twitter-disclaimer.png`],
  },
  robots: {
    index: true, // It's generally good for disclaimers to be indexable
    follow: true,
  },
};

export default function DisclaimerPage() {
  return (
    <div className="container mx-auto min-h-screen flex flex-col items-center justify-center py-10 px-4">
      <Card className="w-full max-w-2xl shadow-lg rounded-xl">
        <CardHeader className="bg-muted/30 p-6">
          <CardTitle className="text-2xl sm:text-3xl font-semibold text-primary">
            Disclaimer for Gita Flow
          </CardTitle>
        </CardHeader>
        <CardContent className="p-6 space-y-6 text-foreground">
          <section aria-labelledby="disclaimer-intro-heading">
            <h2
              id="disclaimer-intro-heading"
              className="text-lg font-semibold mb-2 text-primary/90"
            >
              Nature of Information
            </h2>
            <p>
              Gita Flow provides responses generated by an artificial
              intelligence model. The information and guidance offered are for
              informational and inspirational purposes only and should not be
              considered as professional advice (e.g., psychological, financial,
              legal, or medical).
            </p>
          </section>
          <section aria-labelledby="disclaimer-accuracy-heading">
            <h2
              id="disclaimer-accuracy-heading"
              className="text-lg font-semibold mb-2 text-primary/90"
            >
              Accuracy and Applicability
            </h2>
            <p>
              The AI's responses are based on its training data, which includes
              the Bhagavad Gita and other texts. While we strive for accuracy
              and helpfulness, Gita Flow may produce information that is
              incomplete, inaccurate, or not applicable to your specific
              situation.
            </p>
          </section>
          <section aria-labelledby="disclaimer-responsibility-heading">
            <h2
              id="disclaimer-responsibility-heading"
              className="text-lg font-semibold mb-2 text-primary/90"
            >
              User Responsibility
            </h2>
            <p>
              Users should exercise their own judgment and consult with
              qualified professionals for specific advice tailored to their
              individual circumstances. Reliance on any information provided by
              Gita Flow is solely at your own risk.
            </p>
          </section>
          <section aria-labelledby="disclaimer-liability-heading">
            <h2
              id="disclaimer-liability-heading"
              className="text-lg font-semibold mb-2 text-primary/90"
            >
              Limitation of Liability
            </h2>
            <p>
              The developers of Gita Flow are not responsible for any decisions
              made or actions taken based on the information provided by this
              application. By using Gita Flow, you acknowledge and agree to
              these terms.
            </p>
          </section>
        </CardContent>
      </Card>
      <Button asChild variant="outline" className="mt-8">
        <Link
          href="/"
          className="flex items-center"
          aria-label="Return to Gita Flow homepage"
        >
          <ArrowLeft className="mr-2 h-4 w-4" />
          Return to Gita Flow
        </Link>
      </Button>
    </div>
  );
}
